const swaggerAutogen = require('swagger-autogen')();
const dotenv = require('dotenv');
const HOST = process.env.MONGODB_URL

const schemes = [];

if (HOST == 'localhost:3000') {
    schemes = ['http']
} else {
    schemes = ['https']
}

const doc = {
    info: {
        title: 'Contact API',
        description: 'to Interact with my contacts DB',
    },
    host: HOST,
    schemes: schemes,
};

const outputFile = './swagger-output.json'; // This file will be generated by swagger-autogen
const endpointsFiles = ['./server.js']; //   point to the main server or route files

swaggerAutogen(outputFile, endpointsFiles, doc);